// src/components/linksSearch/Search.tsx
import Fuse from "fuse.js";
import { useMemo, useRef, useState } from "react";
import ResultCard from "./ResultCard";
import type { SearchableLink } from "../../types";

interface Props {
  links: SearchableLink[];
}

interface SearchResult {
  item: SearchableLink;
  refIndex: number;
}

const MIN_SEARCH_SIZE = 3;

export function Search({ links }: Props) {
  const formRef = useRef<HTMLFormElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const [canSubmit, setCanSubmit] = useState(false);
  const [searchResults, setSearchResults] = useState<SearchResult[] | null>(
    null,
  );

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const searchValue = inputRef.current?.value ?? "";
    if (searchValue && searchValue.length >= MIN_SEARCH_SIZE) {
      setSearchResults(episodeFuse.search(searchValue) ?? []);
    }
  };
  const reset = () => {
    if (inputRef.current) inputRef.current.value = "";
    setSearchResults(null);
    inputRef.current?.focus();
    setCanSubmit(false);
  };

  const check = () => {
    if (!inputRef.current) return;

    setCanSubmit(inputRef.current.value.length >= MIN_SEARCH_SIZE);
  };

  const random = () => {
    if (!inputRef.current || !formRef.current) return;
    inputRef.current.value = "pizza";
    formRef.current.requestSubmit();
  };

  const episodeFuse = useMemo(
    () =>
      new Fuse(links, {
        keys: ["episodeTitle", "description"],
        includeMatches: true,
        minMatchCharLength: 2,
        threshold: 0,
        ignoreLocation: true,
      }),
    [links],
  );

  return (
    <>
      <form ref={formRef} onSubmit={handleSubmit}>
        <input
          name="search"
          type="text"
          className="search"
          autoComplete="off"
          placeholder="🍕 Cerca link 🔗 tra gli scontrini..."
          ref={inputRef}
          onChange={check}
        />
        {!Boolean(searchResults) && (
          <div className="row">
            <button className="small" disabled={!canSubmit}>
              Cerca 🔗
            </button>
            <button
              className="small"
              onClick={(e) => {
                e.preventDefault();
                random();
              }}
            >
              Mi sento 🍕
            </button>
          </div>
        )}
      </form>

      {Boolean(searchResults) && (
        <button className="small" onClick={reset}>
          Reset
        </button>
      )}
      {Array.isArray(searchResults) && searchResults.length > 0 && (
        <>
          <div className="results">
            {searchResults.map(({ item, refIndex }) => (
              <ResultCard key={refIndex} link={item} />
            ))}
          </div>
        </>
      )}
      {Array.isArray(searchResults) && searchResults.length < 1 && (
        <div className="resultInfo">
          <h2>Nessun Link Trovato</h2>
          <h1 className="shake">🍕</h1>
        </div>
      )}
    </>
  );
}

// src/components/search/Search.svelte
<script lang="ts">
  import Fuse from "fuse.js";
  import Spinner from "./components/Spinner.svelte";
  import type { IndexedTopic } from "../dataEntry/libs/types";
  let fuse: { tags: Fuse<{ tag: string; episodes: IndexedTopic[] }> };

  function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    if (!canSubmit) return;

    const result = fuse?.tags.search(value);
    searchResults = result.map((r) => ({
      match: r.item.tag,
      episodes: r.item.episodes,
    }));
  }

  function random(e: MouseEvent) {
    e.preventDefault();
    console.log("RANDOM");
  }

  function reset() {
    searchResults = undefined;
    value = "";
  }

  let value = $state("");
  let canSubmit = $derived(value && value.length > 3);
  let searchResults: { match: string; episodes: IndexedTopic[] }[] | undefined =
    $state();

  let loadingFuse = (async () => {
    const r = await fetch("/data/index/tags_episodes.json");
    const tagsIndex = (await r.json()) as Record<string, IndexedTopic[]>;

    fuse = {
      tags: new Fuse(
        Object.entries(tagsIndex).map((e) => {
          return {
            tag: e[0],
            episodes: e[1],
          };
        }),
        { keys: ["tag"], threshold: 0.2 },
      ),
    };
  })();
</script>

{#await loadingFuse}
  <Spinner />
{:then _}
  <form onsubmit={handleSubmit}>
    <input
      name="search"
      type="text"
      class="search"
      autoComplete="off"
      placeholder="🍕 Cerca tra gli episodi..."
      bind:value
    />
    {#if !searchResults}
      <div class="row">
        <button class="small" disabled={!canSubmit}> Cerca 🔍</button>
        <button class="small" onclick={random}> Mi sento 🍕 </button>
      </div>
    {/if}
  </form>

  {#if searchResults}
    <button class="small" onclick={reset}> Reset </button>
  {/if}
  {#if Array.isArray(searchResults) && searchResults.length > 0}
    <ul>
      {#each searchResults as r}
        <li>{r.match}</li>
        <ul>
          {#each r.episodes as e}
            <li>
              {e.episodeTitle} - {e.author}
              {e.section}
              {e.description}
            </li>
          {/each}
        </ul>
      {:else}
        <div class="resultInfo">
          <h2>Nessun Link Trovato</h2>
          <h1 class="shake">🍕</h1>
        </div>
      {/each}
    </ul>
  {/if}
{/await}
